name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
      - name: Testing
        uses: education/autograding@v1
      - name: Uploading reports
        env:
          NLP_2023_SPRING_LEADERBOARD_CREDS: ${{ secrets.NLP_2023_SPRING_LEADERBOARD_CREDS }}
          OWNER: ${{ github.repository }}
        run: python upload_reports.py
